local _, ts = ...

ts.engineeringItems = {
"Accurate Scope",
"Advanced Target Dummy",
"Alarm-O-Bot",
"Aquadynamic Fish Attractor",
"Arcane Bomb",
"Arcanite Dragonling",
"Arcanite Dragonling",
"Arclight Spanner",
"Battle Chicken",
"Big Bronze Bomb",
"Big Iron Bomb",
"Biznicks 247x128 Accurascope",
"Bloodvine Goggles",
"Bloodvine Lens",
"Blue Firework",
"Blue Rocket Cluster",
"Bright-Eye Goggles",
"Bronze Framework",
"Bronze Tube",
"Catseye Ultra Goggles",
"Coarse Blasting Powder",
"Coarse Dynamite",
"Compact Harvest Reaper Kit",
"Copper Modulator",
"Copper Tube",
"Core Marksman Rifle",
"Crafted Heavy Shot",
"Crafted Light Shot",
"Crafted Solid Shot",
"Craftsman",
"Crude Scope",
"Dark Iron Bomb",
"Dark Iron Rifle",
"Deadly Blunderbuss",
"Deadly Scope",
"Deepdive Helmet",
"Delicate Arcanite Converter",
"Dense Blasting Powder",
"Dense Dynamite",
"Dimensional Ripper - Everlook",
"Discombobulator Ray",
"Explosive Sheep",
"EZ-Thro Dynamite",
"EZ-Thro Dynamite II",
"Field Repair Bot 74A",
"Fire Goggles",
"Firework Cluster Launcher",
"Firework Launcher",
"Flame Deflector",
"Flash Bomb",
"Flawless Arcanite Rifle",
"Flying Tiger Goggles",
"Force Reactive Disk",
"Gnomish Battle Chicken",
"Gnomish Cloaking Device",
"Gnomish Death Ray",
"Gnomish Engineer",
"Gnomish Goggles",
"Gnomish Ham Radio",
"Gnomish Harm Prevention Belt",
"Gnomish Mind Control Cap",
"Gnomish Net-o-Matic Projector",
"Gnomish Rocket Boots",
"Gnomish Shrink Ray",
"Gnomish Universal Remote",
"Goblin \"Boom\" Box",
"Goblin Bomb Dispenser",
"Goblin Construction Helmet",
"Goblin Dragon Gun",
"Goblin Engineer",
"Goblin Jumper Cables",
"Goblin Jumper Cables XL",
"Goblin Land Mine",
"Goblin Mining Helmet",
"Goblin Mortar",
"Goblin Radio",
"Goblin Rocket Boots",
"Goblin Rocket Fuel Recipe",
"Goblin Rocket Helmet",
"Goblin Sapper Charge",
"Gold Power Core",
"Green Firework",
"Green Lens",
"Green Rocket Cluster",
"Green Tinted Goggles",
"Gyrochronatom",
"Gyrofreeze Ice Reflector",
"Gyromatic Micro-Adjustor",
"Handful of Copper Bolts",
"Heavy Blasting Powder",
"Heavy Dynamite",
"Hi-Explosive Bomb",
"Hi-Impact Mithril Slugs",
"Hyper-Radiant Flame Reflector",
"Ice Deflector",
"Inlaid Mithril Cylinder Plans",
"Iron Grenade",
"Iron Strut",
"Large Blue Rocket",
"Large Blue Rocket Cluster",
"Large Copper Bomb",
"Large Green Rocket",
"Large Green Rocket Cluster",
"Large Red Rocket",
"Large Red Rocket Cluster",
"Large Seaforium Charge",
"Lifelike Mechanical Toad",
"Lil",
"Lovingly Crafted Boomstick",
"Major Recombobulator",
"Master Engineer",
"Masterwork Target Dummy",
"Mechanical Dragonling",
"Mechanical Dragonling",
"Mechanical Repair Kit",
"Mechanical Squirrel",
"Minor Recombobulator",
"Mithril Blunderbuss",
"Mithril Casing",
"Mithril Frag Bomb",
"Mithril Gyro-Shot",
"Mithril Heavy-bore Rifle",
"Mithril Mechanical Dragonling",
"Mithril Mechanical Dragonling",
"Mithril Tube",
"Mobile Alarm",
"Moonsight Rifle",
"Ornate Spyglass",
"Parachute Cloak",
"Pet Bombling",
"Portable Bronze Mortar",
"Powerful Seaforium Charge",
"Practice Lock",
"Red Firework",
"Red Rocket Cluster",
"Rose Colored Goggles",
"Rough Blasting Powder",
"Rough Boomstick",
"Rough Copper Bomb",
"Rough Dynamite",
"Salt Shaker",
"Shadow Goggles",
"Silver Contact",
"Silver-plated Shotgun",
"Small Blue Rocket",
"Small Bronze Bomb",
"Small Green Rocket",
"Small Red Rocket",
"Small Seaforium Charge",
"Snake Burst Firework",
"Sniper Scope",
"SnowMaster 9000",
"Solid Blasting Powder",
"Solid Dynamite",
"Spellpower Goggles Xtreme",
"Spellpower Goggles Xtreme Plus",
"Standard Scope",
"Steam Tonk Controller",
"Summon Goblin Bomb",
"Target Dummy",
"The Big One",
"The Mortar: Reloaded",
"Thorium Grenade",
"Thorium Rifle",
"Thorium Shells",
"Thorium Tube",
"Thorium Widget",
"Tranquil Mechanical Yeti",
"Truesilver Transformer",
"Ultra-Flash Shadow Reflector",
"Ultrasafe Transporter - Gadgetzan",
"Unstable Trigger",
"Voice Amplification Modulator",
"Whirring Bronze Gizmo",
"World Enlarger"
}
