local _, ts = ...

ts.miningItems = {
    "Copper Ore",
    "Copper Bar",
    "Tin Ore",
    "Tin Bar",
    "Bronze Bar",
    "Silver Ore",
    "Silver Bar",
    "Gold Ore",
    "Gold Bar",
    "Steel Bar",
    "Mithril Ore",
    "Mithril Bar",
    "Truesilver Ore",
    "Truesilver Bar",
    "Thorium Ore",
    "Thorium Bar",
    "Dark Iron Ore",
    "Dark Iron Bar",
    "Elementium Bar",
    "Malachite",
    "Shadowgem",
    "Tigerseye",
    "Jade",
    "Lesser Moonstone",
    "Moss Agate",
    "Blood Shard",
    "Aquamarine",
    "Citrine",
    "Star Ruby",
    "Black Diamond",
    "Blood of the Mountain",
    "Black Vitriol",
    "Arcane Crystal",
    "Azerothian Diamond",
    "Blue Sapphire",
    "Huge Emerald",
    "Large Opal"
}