local _, ts = ...

ts.cookingItems = {
"Baked Salmon",
"Barbecued Buzzard Wing",
"Basic Campfire",
"Beer Basted Boar Ribs",
"Big Bear Steak",
"Blood Sausage",
"Boiled Clams",
"Brilliant Smallfish",
"Bristle Whisker Catfish",
"Carrion Surprise",
"Charred Wolf Meat",
"Clam Chowder",
"Cooked Crab Claw",
"Cooked Glossy Mightfish",
"Cooking",
"Cooking",
"Cooking",
"Cooking",
"Coyote Steak",
"Crab Cake",
"Crispy Bat Wing",
"Crispy Lizard Tail",
"Crocolisk Gumbo",
"Crocolisk Steak",
"Curiously Tasty Omelet",
"Dig Rat Stew",
"Dirge",
"Dragonbreath Chili",
"Dry Pork Ribs",
"Egg Nog",
"Filet of Redgill",
"Fillet of Frenzy",
"Giant Clam Scorcho",
"Gingerbread Cookie",
"Goblin Deviled Clams",
"Goldthorn Tea",
"Gooey Spider Cake",
"Goretusk Liver Pie",
"Grilled Squid",
"Heavy Crocolisk Stew",
"Heavy Kodo Stew",
"Herb Baked Egg",
"Hot Lion Chops",
"Hot Smoked Bass",
"Hot Wolf Ribs",
"Jungle Stew",
"Kaldorei Spider Kabob",
"Lean Venison",
"Lean Wolf Steak",
"Lobster Stew",
"Loch Frenzy Delight",
"Longjaw Mud Snapper",
"Mightfish Steak",
"Mithril Headed Trout",
"Monster Omelet",
"Murloc Fin Soup",
"Mystery Stew",
"Nightfin Soup",
"Poached Sunscale Salmon",
"Rainbow Fin Albacore",
"Redridge Goulash",
"Roast Raptor",
"Roasted Boar Meat",
"Roasted Kodo Meat",
"Rockscale Cod",
"Runn Tum Tuber Surprise",
"Sagefish Delight",
"Savory Deviate Delight",
"Scorpid Surprise",
"Seasoned Wolf Kabob",
"Slitherskin Mackerel",
"Smoked Bear Meat",
"Smoked Desert Dumplings",
"Smoked Sagefish",
"Soothing Turtle Bisque",
"Spiced Chili Crab",
"Spiced Wolf Meat",
"Spider Sausage",
"Spotted Yellowtail",
"Strider Stew",
"Succulent Pork Ribs",
"Tasty Lion Steak",
"Tender Wolf Steak",
"Thistle Tea",
"Undermine Clam Chowder",
"Westfall Stew"
}
