local _, ts = ...

ts.enchantingItems = {
"Brilliant Mana Oil",
"Brilliant Wizard Oil",
"Enchant  Weapon - Healing Power",
"Enchant  Weapon - Spell Power",
"Enchant 2H Weapon - Agility",
"Enchant 2H Weapon - Greater Impact",
"Enchant 2H Weapon - Impact",
"Enchant 2H Weapon - Lesser Impact",
"Enchant 2H Weapon - Lesser Intellect",
"Enchant 2H Weapon - Lesser Spirit",
"Enchant 2H Weapon - Major Intellect",
"Enchant 2H Weapon - Major Spirit",
"Enchant 2H Weapon - Minor Impact",
"Enchant 2H Weapon - Superior Impact",
"Enchant Boots - Agility",
"Enchant Boots - Greater Agility",
"Enchant Boots - Greater Stamina",
"Enchant Boots - Lesser Agility",
"Enchant Boots - Lesser Spirit",
"Enchant Boots - Lesser Stamina",
"Enchant Boots - Minor Agility",
"Enchant Boots - Minor Speed",
"Enchant Boots - Minor Stamina",
"Enchant Boots - Spirit",
"Enchant Boots - Stamina",
"Enchant Bracer - Deflection",
"Enchant Bracer - Greater Intellect",
"Enchant Bracer - Greater Spirit",
"Enchant Bracer - Greater Stamina",
"Enchant Bracer - Greater Strength",
"Enchant Bracer - Healing Power",
"Enchant Bracer - Intellect",
"Enchant Bracer - Lesser Deflection",
"Enchant Bracer - Lesser Intellect",
"Enchant Bracer - Lesser Spirit",
"Enchant Bracer - Lesser Stamina",
"Enchant Bracer - Lesser Strength",
"Enchant Bracer - Mana Regeneration",
"Enchant Bracer - Minor Agility",
"Enchant Bracer - Minor Deflect",
"Enchant Bracer - Minor Health",
"Enchant Bracer - Minor Spirit",
"Enchant Bracer - Minor Stamina",
"Enchant Bracer - Minor Strength",
"Enchant Bracer - Spirit",
"Enchant Bracer - Stamina",
"Enchant Bracer - Strength",
"Enchant Bracer - Superior Spirit",
"Enchant Bracer - Superior Stamina",
"Enchant Bracer - Superior Strength",
"Enchant Chest - Greater Health",
"Enchant Chest - Greater Mana",
"Enchant Chest - Greater Stats",
"Enchant Chest - Health",
"Enchant Chest - Lesser Absorption",
"Enchant Chest - Lesser Health",
"Enchant Chest - Lesser Mana",
"Enchant Chest - Lesser Stats",
"Enchant Chest - Major Health",
"Enchant Chest - Major Mana",
"Enchant Chest - Mana",
"Enchant Chest - Minor Absorption",
"Enchant Chest - Minor Health",
"Enchant Chest - Minor Mana",
"Enchant Chest - Minor Stats",
"Enchant Chest - Stats",
"Enchant Chest - Superior Health",
"Enchant Chest - Superior Mana",
"Enchant Cloak - Defense",
"Enchant Cloak - Dodge",
"Enchant Cloak - Fire Resistance",
"Enchant Cloak - Greater Defense",
"Enchant Cloak - Greater Fire Resistance",
"Enchant Cloak - Greater Nature Resistance",
"Enchant Cloak - Greater Resistance",
"Enchant Cloak - Lesser Agility",
"Enchant Cloak - Lesser Fire Resistance",
"Enchant Cloak - Lesser Protection",
"Enchant Cloak - Lesser Shadow Resistance",
"Enchant Cloak - Minor Agility",
"Enchant Cloak - Minor Protection",
"Enchant Cloak - Minor Resistance",
"Enchant Cloak - Resistance",
"Enchant Cloak - Stealth",
"Enchant Cloak - Subtlety",
"Enchant Cloak - Superior Defense",
"Enchant Gloves - Advanced Herbalism",
"Enchant Gloves - Advanced Mining",
"Enchant Gloves - Agility",
"Enchant Gloves - Fire Power",
"Enchant Gloves - Fishing",
"Enchant Gloves - Frost Power",
"Enchant Gloves - Greater Agility",
"Enchant Gloves - Greater Strength",
"Enchant Gloves - Healing Power",
"Enchant Gloves - Herbalism",
"Enchant Gloves - Mining",
"Enchant Gloves - Minor Haste",
"Enchant Gloves - Riding Skill",
"Enchant Gloves - Shadow Power",
"Enchant Gloves - Skinning",
"Enchant Gloves - Strength",
"Enchant Gloves - Superior Agility",
"Enchant Gloves - Threat",
"Enchant Shield - Frost Resistance",
"Enchant Shield - Greater Spirit",
"Enchant Shield - Greater Stamina",
"Enchant Shield - Lesser Block",
"Enchant Shield - Lesser Protection",
"Enchant Shield - Lesser Spirit",
"Enchant Shield - Lesser Stamina",
"Enchant Shield - Minor Stamina",
"Enchant Shield - Spirit",
"Enchant Shield - Stamina",
"Enchant Shield - Superior Spirit",
"Enchant Weapon - Agility",
"Enchant Weapon - Crusader",
"Enchant Weapon - Demonslaying",
"Enchant Weapon - Fiery Weapon",
"Enchant Weapon - Greater Striking",
"Enchant Weapon - Icy Chill",
"Enchant Weapon - Lesser Beastslayer",
"Enchant Weapon - Lesser Elemental Slayer",
"Enchant Weapon - Lesser Striking",
"Enchant Weapon - Lifestealing",
"Enchant Weapon - Mighty Intellect",
"Enchant Weapon - Mighty Spirit",
"Enchant Weapon - Minor Beastslayer",
"Enchant Weapon - Minor Striking",
"Enchant Weapon - Strength",
"Enchant Weapon - Striking",
"Enchant Weapon - Superior Striking",
"Enchant Weapon - Unholy Weapon",
"Enchant Weapon - Winter",
"Enchanted Leather",
"Enchanted Thorium",
"Greater Magic Wand",
"Greater Mystic Wand",
"Lesser Magic Wand",
"Lesser Mana Oil",
"Lesser Mystic Wand",
"Lesser Wizard Oil",
"Minor Mana Oil",
"Minor Wizard Oil",
"Runed Arcanite Rod",
"Runed Copper Rod",
"Runed Golden Rod",
"Runed Silver Rod",
"Runed Truesilver Rod",
"Smoking Heart of the Mountain",
"Wizard Oil",

--Manually added Mats
"Strange Dust",
"Lesser Magic Essence",
"Greater Magic Essence",
"Small Glimmering Shard",
"Lesser Astral Essence",
"Lesser Mystic Essence",
"Soul Dust",
"Large Glimmering Shard",
"Greater Astral Essence",
"Greater Mystic Essence",
"Large Glowing Shard",
"Lesser Nether Essence",
"Vision Dust",
"Lesser Eternal Essence",
"Dream Dust",
"Greater Nether Essence",
"Small Radiant Shard",
"Large Radiant Shard",
"Greater Nether Essence",
"Small Glowing Shard",
"Illusion Dust",
"Greater Eternal Essence",
"Small Brilliant Shard",
"Large Brilliant Shard",
"Nexus Crystal"
}