local _, ts = ...

ts.herbalismItems = {
"Peacebloom",
"Silverleaf",
"Earthroot",
"Mageroyal",
"Swiftthistle",
"Briarthorn",
"Stranglekelp",
"Bruiseweed",
"Wild Steelbloom",
"Grave Moss",
"Kingsblood",
"Liferoot",
"Fadeleaf",
"Goldthorn",
"Khadgar's Whisker",
"Wintersbite",
"Firebloom",
"Purple Lotus",
"Wildvine",
"Arthas' Tears",
"Sungrass",
"Blindweed",
"Ghost Mushroom",
"Gromsblood",
"Golden Sansam",
"Dreamfoil",
"Mountain Silversage",
"Plaguebloom",
"Icecap",
"Black Lotus",
}