local _, ts = ...

ts.leatherworkingItems = {
    "Barbaric Belt",
"Barbaric Bracers",
"Barbaric Gloves",
"Barbaric Harness",
"Barbaric Leggings",
"Barbaric Shoulders",
"Big Voodoo Cloak",
"Big Voodoo Mask",
"Big Voodoo Pants",
"Big Voodoo Robe",
"Black Dragonscale Boots",
"Black Dragonscale Breastplate",
"Black Dragonscale Leggings",
"Black Dragonscale Shoulders",
"Black Whelp Cloak",
"Black Whelp Tunic",
"Blood Tiger Breastplate",
"Blood Tiger Shoulders",
"Blue Dragonscale Breastplate",
"Blue Dragonscale Leggings",
"Blue Dragonscale Shoulders",
"Bramblewood Belt",
"Bramblewood Boots",
"Bramblewood Helm",
"Chimeric Boots",
"Chimeric Gloves",
"Chimeric Leggings",
"Chimeric Vest",
"Chromatic Cloak",
"Chromatic Gauntlets",
"Comfortable Leather Hat",
"Core Armor Kit",
"Corehound Belt",
"Corehound Boots",
"Cured Heavy Hide",
"Cured Light Hide",
"Cured Medium Hide",
"Cured Rugged Hide",
"Cured Thick Hide",
"Dark Leather Belt",
"Dark Leather Boots",
"Dark Leather Cloak",
"Dark Leather Gloves",
"Dark Leather Pants",
"Dark Leather Shoulders",
"Dark Leather Tunic",
"Dawn Treaders",
"Deviate Scale Belt",
"Deviate Scale Cloak",
"Deviate Scale Gloves",
"Devilsaur Gauntlets",
"Devilsaur Leggings",
"Dragonscale Breastplate",
"Dragonscale Gauntlets",
"Dragonscale Leatherworking",
"Dreamscale Breastplate",
"Dusky Belt",
"Dusky Boots",
"Dusky Bracers",
"Dusky Leather Armor",
"Dusky Leather Leggings",
"Earthen Leather Shoulders",
"Elemental Leatherworking",
"Embossed Leather Boots",
"Embossed Leather Cloak",
"Embossed Leather Gloves",
"Embossed Leather Pants",
"Embossed Leather Vest",
"Feathered Breastplate",
"Fine Leather Belt",
"Fine Leather Boots",
"Fine Leather Cloak",
"Fine Leather Gloves",
"Fine Leather Pants",
"Fine Leather Tunic",
"Fletcher",
"Frost Leather Cloak",
"Frostsaber Boots",
"Frostsaber Gloves",
"Frostsaber Leggings",
"Frostsaber Tunic",
"Gauntlets of the Sea",
"Gem-studded Leather Belt",
"Girdle of Insight",
"Gloves of the Greatfather",
"Golden Mantle of the Dawn",
"Gordok Ogre Suit",
"Green Dragonscale Breastplate",
"Green Dragonscale Gauntlets",
"Green Dragonscale Leggings",
"Green Leather Armor",
"Green Leather Belt",
"Green Leather Bracers",
"Green Whelp Armor",
"Green Whelp Bracers",
"Guardian Armor",
"Guardian Belt",
"Guardian Cloak",
"Guardian Gloves",
"Guardian Leather Bracers",
"Guardian Pants",
"Handstitched Leather Belt",
"Handstitched Leather Boots",
"Handstitched Leather Bracers",
"Handstitched Leather Cloak",
"Handstitched Leather Pants",
"Handstitched Leather Vest",
"Heavy Armor Kit",
"Heavy Earthen Gloves",
"Heavy Leather",
"Heavy Leather Ammo Pouch",
"Heavy Leather Ball",
"Heavy Quiver",
"Heavy Scorpid Belt",
"Heavy Scorpid Bracers",
"Heavy Scorpid Gauntlets",
"Heavy Scorpid Helm",
"Heavy Scorpid Leggings",
"Heavy Scorpid Shoulders",
"Heavy Scorpid Vest",
"Helm of Fire",
"Herbalist",
"Hide of the Wild",
"Hillman",
"Hillman",
"Hillman",
"Hillman",
"Hillman",
"Icy Scale Bracers",
"Icy Scale Breastplate",
"Icy Scale Gauntlets",
"Ironfeather Breastplate",
"Ironfeather Shoulders",
"Kodo Hide Bag",
"Lava Belt",
"Leatherworking",
"Leatherworking",
"Leatherworking",
"Leatherworking",
"Light Armor Kit",
"Light Leather",
"Light Leather Bracers",
"Light Leather Pants",
"Light Leather Quiver",
"Living Breastplate",
"Living Leggings",
"Living Shoulders",
"Medium Armor Kit",
"Medium Leather",
"Might of the Timbermaw",
"Molten Belt",
"Molten Helm",
"Mongoose Boots",
"Moonglow Vest",
"Murloc Scale Belt",
"Murloc Scale Bracers",
"Murloc Scale Breastplate",
"Nightscape Boots",
"Nightscape Cloak",
"Nightscape Headband",
"Nightscape Pants",
"Nightscape Shoulders",
"Nightscape Tunic",
"Nimble Leather Gloves",
"Onyxia Scale Breastplate",
"Onyxia Scale Cloak",
"Pilferer",
"Polar Bracers",
"Polar Gloves",
"Polar Tunic",
"Primal Batskin Bracers",
"Primal Batskin Gloves",
"Primal Batskin Jerkin",
"Quickdraw Quiver",
"Raptor Hide Belt",
"Raptor Hide Harness",
"Red Dragonscale Breastplate",
"Red Whelp Gloves",
"Rugged Armor Kit",
"Rugged Leather",
"Rugged Leather Pants",
"Runic Leather Armor",
"Runic Leather Belt",
"Runic Leather Bracers",
"Runic Leather Gauntlets",
"Runic Leather Headband",
"Runic Leather Pants",
"Runic Leather Shoulders",
"Sandstalker Bracers",
"Sandstalker Breastplate",
"Sandstalker Gauntlets",
"Shadowskin Gloves",
"Shifting Cloak",
"Small Leather Ammo Pouch",
"Spitfire Bracers",
"Spitfire Breastplate",
"Spitfire Gauntlets",
"Stormshroud Armor",
"Stormshroud Gloves",
"Stormshroud Pants",
"Stormshroud Shoulders",
"Swift Boots",
"Swift Flight Bracers",
"Thick Armor Kit",
"Thick Leather",
"Thick Leather Ammo Pouch",
"Thick Murloc Armor",
"Timbermaw Brawlers",
"Tough Scorpid Boots",
"Tough Scorpid Bracers",
"Tough Scorpid Breastplate",
"Tough Scorpid Gloves",
"Tough Scorpid Helm",
"Tough Scorpid Leggings",
"Tough Scorpid Shoulders",
"Toughened Leather Armor",
"Toughened Leather Gloves",
"Tribal Leatherworking",
"Turtle Scale Bracers",
"Turtle Scale Breastplate",
"Turtle Scale Gloves",
"Turtle Scale Helm",
"Turtle Scale Leggings",
"Volcanic Breastplate",
"Volcanic Leggings",
"Volcanic Shoulders",
"Warbear Harness",
"Warbear Woolies",
"White Leather Jerkin",
"Wicked Leather Armor",
"Wicked Leather Belt",
"Wicked Leather Bracers",
"Wicked Leather Gauntlets",
"Wicked Leather Headband",
"Wicked Leather Pants",
"Wild Leather Boots",
"Wild Leather Cloak",
"Wild Leather Helmet",
"Wild Leather Leggings",
"Wild Leather Shoulders",
"Wild Leather Vest",
"Wolfshead Helm"
}
