
local _, ts = ...

ts.tailoringItems = {
    "Admiral",
"Argent Boots",
"Argent Shoulders",
"Azure Shoulders",
"Azure Silk Belt",
"Azure Silk Cloak",
"Azure Silk Gloves",
"Azure Silk Hood",
"Azure Silk Pants",
"Azure Silk Vest",
"Barbaric Linen Vest",
"Belt of the Archmage",
"Big Bag of Enchantment",
"Black Mageweave Boots",
"Black Mageweave Gloves",
"Black Mageweave Headband",
"Black Mageweave Leggings",
"Black Mageweave Robe",
"Black Mageweave Shoulders",
"Black Mageweave Vest",
"Black Silk Pack",
"Black Swashbuckler",
"Bloodvine Boots",
"Bloodvine Leggings",
"Bloodvine Vest",
"Blue Linen Robe",
"Blue Linen Shirt",
"Blue Linen Vest",
"Blue Overalls",
"Bolt of Linen Cloth",
"Bolt of Mageweave",
"Bolt of Runecloth",
"Bolt of Silk Cloth",
"Bolt of Woolen Cloth",
"Boots of Darkness",
"Boots of the Enchanter",
"Bottomless Bag",
"Bright Yellow Shirt",
"Brightcloth Cloak",
"Brightcloth Gloves",
"Brightcloth Pants",
"Brightcloth Robe",
"Brown Linen Pants",
"Brown Linen Robe",
"Brown Linen Shirt",
"Brown Linen Vest",
"Cenarion Herb Bag",
"Cindercloth Boots",
"Cindercloth Cloak",
"Cindercloth Gloves",
"Cindercloth Pants",
"Cindercloth Robe",
"Cindercloth Vest",
"Cloak of Fire",
"Cloak of Warding",
"Colorful Kilt",
"Core Felcloth Bag",
"Crimson Silk Belt",
"Crimson Silk Cloak",
"Crimson Silk Gloves",
"Crimson Silk Pantaloons",
"Crimson Silk Robe",
"Crimson Silk Shoulders",
"Crimson Silk Vest",
"Dark Silk Shirt",
"Double-stitched Woolen Shoulders",
"Dreamweave Circlet",
"Dreamweave Gloves",
"Dreamweave Vest",
"Earthen Silk Belt",
"Earthen Vest",
"Enchanted Mageweave Pouch",
"Enchanted Runecloth Bag",
"Enchanter",
"Felcloth Bag",
"Felcloth Boots",
"Felcloth Gloves",
"Felcloth Hood",
"Felcloth Pants",
"Felcloth Robe",
"Felcloth Shoulders",
"Festive Red Dress",
"Festive Red Pant Suit",
"Flarecore Gloves",
"Flarecore Leggings",
"Flarecore Mantle",
"Flarecore Robe",
"Flarecore Wraps",
"Formal White Shirt",
"Frostweave Gloves",
"Frostweave Pants",
"Frostweave Robe",
"Frostweave Tunic",
"Gaea",
"Ghostweave Belt",
"Ghostweave Gloves",
"Ghostweave Pants",
"Ghostweave Vest",
"Glacial Cloak",
"Glacial Gloves",
"Glacial Vest",
"Glacial Wrists",
"Gloves of Meditation",
"Gloves of Spell Mastery",
"Gordok Ogre Suit",
"Gray Woolen Robe",
"Gray Woolen Shirt",
"Greater Adept",
"Green Holiday Shirt",
"Green Linen Bracers",
"Green Linen Shirt",
"Green Silk Armor",
"Green Silk Pack",
"Green Silken Shoulders",
"Green Woolen Bag",
"Green Woolen Robe",
"Green Woolen Vest",
"Hands of Darkness",
"Handstitched Linen Britches",
"Heavy Linen Gloves",
"Heavy Woolen Cloak",
"Heavy Woolen Gloves",
"Heavy Woolen Pants",
"Icy Cloak",
"Inferno Gloves",
"Lavender Mageweave Shirt",
"Lesser Wizard",
"Linen Bag",
"Linen Belt",
"Linen Boots",
"Linen Cloak",
"Long Silken Cloak",
"Mageweave Bag",
"Mantle of the Timbermaw",
"Mooncloth",
"Mooncloth Bag",
"Mooncloth Boots",
"Mooncloth Circlet",
"Mooncloth Gloves",
"Mooncloth Leggings",
"Mooncloth Robe",
"Mooncloth Shoulders",
"Mooncloth Vest",
"Orange Mageweave Shirt",
"Orange Martial Shirt",
"Pearl-clasped Cloak",
"Phoenix Gloves",
"Phoenix Pants",
"Pink Mageweave Shirt",
"Red Linen Bag",
"Red Linen Robe",
"Red Linen Shirt",
"Red Linen Vest",
"Red Mageweave Bag",
"Red Mageweave Gloves",
"Red Mageweave Headband",
"Red Mageweave Pants",
"Red Mageweave Shoulders",
"Red Mageweave Vest",
"Red Swashbuckler",
"Red Woolen Bag",
"Red Woolen Boots",
"Reinforced Linen Cape",
"Reinforced Woolen Shoulders",
"Rich Purple Silk Shirt",
"Robe of Power",
"Robe of the Archmage",
"Robe of the Void",
"Robe of Winter Night",
"Robes of Arcana",
"Runecloth Bag",
"Runecloth Belt",
"Runecloth Boots",
"Runecloth Cloak",
"Runecloth Gloves",
"Runecloth Headband",
"Runecloth Pants",
"Runecloth Robe",
"Runecloth Shoulders",
"Runecloth Tunic",
"Runed Stygian Belt",
"Runed Stygian Boots",
"Runed Stygian Leggings",
"Satchel of Cenarius",
"Shadow Hood",
"Shadoweave Boots",
"Shadoweave Gloves",
"Shadoweave Mask",
"Shadoweave Pants",
"Shadoweave Robe",
"Shadoweave Shoulders",
"Silk Headband",
"Simple Black Dress",
"Simple Dress",
"Simple Kilt",
"Simple Linen Boots",
"Simple Linen Pants",
"Small Silk Pack",
"Soft-soled Linen Boots",
"Soul Pouch",
"Spider Belt",
"Spider Silk Slippers",
"Spidersilk Boots",
"Star Belt",
"Stormcloth Boots",
"Stormcloth Gloves",
"Stormcloth Headband",
"Stormcloth Pants",
"Stormcloth Shoulders",
"Stormcloth Vest",
"Stylish Blue Shirt",
"Stylish Green Shirt",
"Stylish Red Shirt",
"Sylvan Crown",
"Sylvan Shoulders",
"Sylvan Vest",
"Truefaith Gloves",
"Truefaith Vestments",
"Tuxedo Jacket",
"Tuxedo Pants",
"Tuxedo Shirt",
"White Bandit Mask",
"White Linen Robe",
"White Linen Shirt",
"White Swashbuckler",
"White Wedding Dress",
"White Woolen Dress",
"Wisdom of the Timbermaw",
"Wizardweave Leggings",
"Wizardweave Robe",
"Wizardweave Turban",
"Woolen Bag",
"Woolen Boots",
"Woolen Cape"
}